/* The following code was generated by JFlex 1.7.0 */

package analizadorLexico;
import java_cup.runtime.*;
import java.lang.*;

public class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\13\1\15\1\14\1\14\22\0\1\3\1\25\1\12"+
    "\3\0\1\26\1\0\1\31\1\32\1\17\1\22\1\0\1\5\1\6"+
    "\1\16\1\7\1\11\10\2\1\20\1\30\1\24\1\21\1\23\2\0"+
    "\32\1\4\0\1\4\1\0\1\47\1\10\2\1\1\44\1\35\1\1"+
    "\1\41\1\42\1\1\1\50\1\43\2\1\1\36\2\1\1\37\1\45"+
    "\1\46\2\1\1\40\3\1\1\33\1\27\1\34\7\0\1\15\u1fa2\0"+
    "\1\15\1\15\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\1\1\3"+
    "\1\1\1\6\1\7\2\1\1\10\1\11\1\12\1\13"+
    "\2\1\1\14\1\15\1\16\1\17\1\20\5\2\1\21"+
    "\3\0\1\22\2\0\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\3\2\1\32\2\2\1\33\1\0\1\22"+
    "\1\4\1\0\1\34\4\2\1\0\1\22\2\2\1\35"+
    "\1\36\1\0\1\22\1\37\1\40\1\0\1\22\1\0"+
    "\1\22\1\0\1\22\1\0\1\22\1\0\1\22\1\0"+
    "\1\22\1\0\1\22\1\0\1\22\1\0\1\22\1\0"+
    "\1\22\1\0\1\22\1\0\1\22\1\0\1\22\1\0"+
    "\1\22\1\0\1\22\1\0\1\22\1\0\1\22\1\0"+
    "\1\22\1\0\1\22\1\0\1\22\1\0\1\22\1\0"+
    "\1\22\1\0\1\22\1\0\1\22\1\0\1\22\1\0"+
    "\2\22";

  private static int [] zzUnpackAction() {
    int [] result = new int[122];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\51\0\122\0\173\0\244\0\315\0\366\0\u011f"+
    "\0\u0148\0\u0171\0\51\0\u019a\0\u01c3\0\51\0\u01ec\0\u0215"+
    "\0\u023e\0\u0267\0\u0290\0\51\0\51\0\51\0\51\0\51"+
    "\0\u02b9\0\u02e2\0\u030b\0\u0334\0\u035d\0\366\0\366\0\u0386"+
    "\0\u03af\0\u03af\0\u03d8\0\u0401\0\51\0\51\0\51\0\51"+
    "\0\51\0\51\0\51\0\u042a\0\u0453\0\u047c\0\122\0\u04a5"+
    "\0\u04ce\0\u0386\0\u04f7\0\u04f7\0\51\0\u0520\0\122\0\u0549"+
    "\0\u0572\0\u059b\0\u05c4\0\u05ed\0\u05ed\0\u0616\0\u063f\0\122"+
    "\0\122\0\u0668\0\u0668\0\122\0\122\0\u0691\0\u0691\0\u06ba"+
    "\0\u06ba\0\u06e3\0\u06e3\0\u070c\0\u070c\0\u0735\0\u0735\0\u075e"+
    "\0\u075e\0\u0787\0\u0787\0\u07b0\0\u07b0\0\u07d9\0\u07d9\0\u0802"+
    "\0\u0802\0\u082b\0\u082b\0\u0854\0\u0854\0\u087d\0\u087d\0\u08a6"+
    "\0\u08a6\0\u08cf\0\u08cf\0\u08f8\0\u08f8\0\u0921\0\u0921\0\u094a"+
    "\0\u094a\0\u0973\0\u0973\0\u099c\0\u099c\0\u09c5\0\u09c5\0\u09ee"+
    "\0\u09ee\0\u0a17\0\u0a17\0\u0a40\0\u0a40\0\u0a69\0\u0a69\0\u0a92"+
    "\0\u0a92\0\51";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[122];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\3\1\6\1\7\1\10"+
    "\1\3\1\4\1\11\2\5\1\2\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\2\3\1\32\1\3"+
    "\1\33\1\3\1\34\1\3\1\35\2\3\52\0\2\3"+
    "\4\0\3\3\23\0\14\3\2\0\1\4\3\0\1\36"+
    "\1\4\1\0\1\4\42\0\1\5\7\0\2\5\36\0"+
    "\1\4\3\0\1\37\1\4\1\0\1\4\41\0\1\36"+
    "\4\0\1\36\1\0\1\36\41\0\1\4\3\0\1\36"+
    "\1\4\1\40\1\4\37\0\12\41\1\42\3\0\33\41"+
    "\16\0\1\43\1\44\52\0\1\45\50\0\1\46\50\0"+
    "\1\47\50\0\1\50\50\0\1\51\55\0\1\52\51\0"+
    "\1\53\22\0\2\3\4\0\3\3\23\0\1\3\1\54"+
    "\12\3\1\0\2\3\4\0\3\3\23\0\2\3\1\55"+
    "\1\3\1\56\7\3\1\0\2\3\4\0\3\3\23\0"+
    "\1\57\13\3\1\0\2\3\4\0\3\3\23\0\6\3"+
    "\1\60\5\3\1\0\2\3\4\0\3\3\23\0\12\3"+
    "\1\61\1\3\7\0\1\62\1\0\1\62\37\0\12\63"+
    "\1\64\3\0\33\63\13\43\1\65\35\43\17\44\1\66"+
    "\31\44\1\0\2\3\4\0\3\3\23\0\2\3\1\67"+
    "\11\3\1\0\2\3\4\0\3\3\23\0\5\3\1\70"+
    "\6\3\1\0\2\3\4\0\3\3\23\0\5\3\1\71"+
    "\6\3\1\0\2\3\4\0\3\3\23\0\10\3\1\72"+
    "\3\3\1\0\2\3\4\0\3\3\23\0\13\3\1\73"+
    "\12\74\1\75\3\0\33\74\16\44\1\65\1\66\31\44"+
    "\1\0\2\3\4\0\3\3\23\0\11\3\1\76\2\3"+
    "\1\0\2\3\4\0\3\3\23\0\6\3\1\77\5\3"+
    "\1\0\2\3\4\0\3\3\23\0\7\3\1\100\4\3"+
    "\1\0\2\3\4\0\3\3\23\0\7\3\1\101\4\3"+
    "\12\102\1\103\3\0\33\102\1\0\2\3\4\0\3\3"+
    "\23\0\7\3\1\104\4\3\1\0\2\3\4\0\3\3"+
    "\23\0\7\3\1\105\4\3\12\106\1\107\3\0\33\106"+
    "\12\110\1\111\3\0\33\110\12\112\1\113\3\0\33\112"+
    "\12\114\1\115\3\0\33\114\12\116\1\117\3\0\33\116"+
    "\12\120\1\121\3\0\33\120\12\122\1\123\3\0\33\122"+
    "\12\124\1\125\3\0\33\124\12\126\1\127\3\0\33\126"+
    "\12\130\1\131\3\0\33\130\12\132\1\133\3\0\33\132"+
    "\12\134\1\135\3\0\33\134\12\136\1\137\3\0\33\136"+
    "\12\140\1\141\3\0\33\140\12\142\1\143\3\0\33\142"+
    "\12\144\1\145\3\0\33\144\12\146\1\147\3\0\33\146"+
    "\12\150\1\151\3\0\33\150\12\152\1\153\3\0\33\152"+
    "\12\154\1\155\3\0\33\154\12\156\1\157\3\0\33\156"+
    "\12\160\1\161\3\0\33\160\12\162\1\163\3\0\33\162"+
    "\12\164\1\165\3\0\33\164\12\166\1\167\3\0\33\166"+
    "\12\170\1\171\3\0\33\170\12\0\1\172\36\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2747];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\10\1\1\11\2\1\1\11\5\1\5\11"+
    "\6\1\3\0\1\1\2\0\7\11\7\1\1\0\1\1"+
    "\1\11\1\0\5\1\1\0\5\1\1\0\3\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[122];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 158) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return null; }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new Error("Caracter inválido: <" + yytext() + "> en la linea " + yyline);
            } 
            // fall through
          case 33: break;
          case 2: 
            { System.out.println("Token ID encontrado, lexema " + yytext());
            } 
            // fall through
          case 34: break;
          case 3: 
            {
              try {
                int valor = Integer.parseInt(yytext());
                if (valor < -32768 || valor > 32767) {
                  throw new Error("Valor fuera del rango de 16 bits: " + yytext() + " en linea " + yyline);
                } else {
                  System.out.println("Token CONST_INT encontrado, lexema " + yytext());
                }
              }
              catch (NumberFormatException e) {
                throw new Error("Valor fuera del rango de 16 bits: " + yytext() + " en linea " + yyline);
              }
            } 
            // fall through
          case 35: break;
          case 4: 
            { 
            } 
            // fall through
          case 36: break;
          case 5: 
            { System.out.println("Token RESTA encontrado, lexema " + yytext());
            } 
            // fall through
          case 37: break;
          case 6: 
            { System.out.println("Token DIVISIÓN encontrado, lexema " + yytext());
            } 
            // fall through
          case 38: break;
          case 7: 
            { System.out.println("Token PRODUCTO encontrado, lexema " + yytext());
            } 
            // fall through
          case 39: break;
          case 8: 
            { System.out.println("Token SUMA encontrado, lexema " + yytext());
            } 
            // fall through
          case 40: break;
          case 9: 
            { System.out.println("Token MAYOR encontrado, lexema " + yytext());
            } 
            // fall through
          case 41: break;
          case 10: 
            { System.out.println("Token MENOR encontrado, lexema " + yytext());
            } 
            // fall through
          case 42: break;
          case 11: 
            { System.out.println("Token NEGADOR encontrado, lexema " + yytext());
            } 
            // fall through
          case 43: break;
          case 12: 
            { System.out.println("Token END_LINE encontrado, lexema " + yytext());
            } 
            // fall through
          case 44: break;
          case 13: 
            { System.out.println("Token PAR_A encontrado, lexema " + yytext());
            } 
            // fall through
          case 45: break;
          case 14: 
            { System.out.println("Token PAR_C encontrado, lexema " + yytext());
            } 
            // fall through
          case 46: break;
          case 15: 
            { System.out.println("Token COR_A encontrado, lexema " + yytext());
            } 
            // fall through
          case 47: break;
          case 16: 
            { System.out.println("Token COR_C encontrado, lexema " + yytext());
            } 
            // fall through
          case 48: break;
          case 17: 
            { try {
                float valor = Float.parseFloat(yytext());
                if (valor < -3.4028235E38|| valor > 3.4028235E38) {
                  throw new Error("Valor fuera del rango de 32 bits: " + yytext() + " en linea " + yyline);
                } else {
                  System.out.println("Token CONST_FLOAT encontrado, lexema " + yytext());
                }
              } catch (NumberFormatException e){
                throw new Error("Valor fuera del rango de 32 bits: " + yytext() + " en linea " + yyline);
              }
            }
            // fall through
          case 49: break;
          case 18: 
            { String value = yytext();
        if (value.length() > 32) {
            throw new Error("Valor supera cant. máx. de caracteres: " + yytext() + " en linea " + yyline);
        } else {
            System.out.println("Token CONST_STR encontrado, lexema " + yytext());
        }
            } 
            // fall through
          case 50: break;
          case 19: 
            { System.out.println("Token ASSIGN encontrado, lexema " + yytext());
            } 
            // fall through
          case 51: break;
          case 20: 
            { System.out.println("Token COMPARADOR_IGUAL encontrado, lexema " + yytext());
            } 
            // fall through
          case 52: break;
          case 21: 
            { System.out.println("Token MAYOR_IGUAL encontrado, lexema " + yytext());
            } 
            // fall through
          case 53: break;
          case 22: 
            { System.out.println("Token MENOR_IGUAL encontrado, lexema " + yytext());
            } 
            // fall through
          case 54: break;
          case 23: 
            { System.out.println("Token DISTINTO encontrado, lexema " + yytext());
            } 
            // fall through
          case 55: break;
          case 24: 
            { System.out.println("Token AND encontrado, lexema " + yytext());
            } 
            // fall through
          case 56: break;
          case 25: 
            { System.out.println("Token OR encontrado, lexema " + yytext());
            } 
            // fall through
          case 57: break;
          case 26: 
            { System.out.println("Token IF encontrado, lexema " + yytext());
            } 
            // fall through
          case 58: break;
          case 27: 
            { System.out.println("Token CONST_BIN encontrado, lexema " + yytext());
            } 
            // fall through
          case 59: break;
          case 28: 
            { System.out.println("Token FOR encontrado, lexema " + yytext());
            } 
            // fall through
          case 60: break;
          case 29: 
            { System.out.println("Token ELSE encontrado, lexema " + yytext());
            } 
            // fall through
          case 61: break;
          case 30: 
            { System.out.println("Token TAKE encontrado, lexema " + yytext());
            } 
            // fall through
          case 62: break;
          case 31: 
            { System.out.println("Token WRITE encontrado, lexema " + yytext());
            } 
            // fall through
          case 63: break;
          case 32: 
            { System.out.println("Token WHILE encontrado, lexema " + yytext());
            } 
            // fall through
          case 64: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
