
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 26 08:22:40 GMT-03:00 2024
//----------------------------------------------------

package analizadorLexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ENDDECLARE_SECTION = 27;
  public static final int DISTINTO = 21;
  public static final int COR_CIERRE = 13;
  public static final int TIPO_STRING = 34;
  public static final int END_LINE = 30;
  public static final int WRITE = 14;
  public static final int AND = 22;
  public static final int IGUAL = 19;
  public static final int OR = 25;
  public static final int CONST_FLOAT = 40;
  public static final int IF = 3;
  public static final int ID = 36;
  public static final int CONST_BIN = 37;
  public static final int EOF = 0;
  public static final int OP_DIVISION = 11;
  public static final int error = 1;
  public static final int NEGACION = 20;
  public static final int MENOR = 16;
  public static final int OP_RESTA = 10;
  public static final int TIPO_INT = 32;
  public static final int PAR_APERTURA = 23;
  public static final int MAYOR = 15;
  public static final int DECLARA = 7;
  public static final int SEP_LIST = 31;
  public static final int ELSE = 5;
  public static final int TAKE = 35;
  public static final int COR_APERTURA = 12;
  public static final int WHILE = 2;
  public static final int MAYOR_IGUAL = 17;
  public static final int THEN = 4;
  public static final int TIPO_FLOAT = 33;
  public static final int PROGRAM_SECTION = 28;
  public static final int ASIGN = 6;
  public static final int ENDPROGRAM_SECTION = 29;
  public static final int CONST_STR = 39;
  public static final int PAR_CIERRE = 24;
  public static final int OP_SUMA = 8;
  public static final int MENOR_IGUAL = 18;
  public static final int OP_POR = 9;
  public static final int CONST_INT = 38;
  public static final int DECLARE_SECTION = 26;
}

